source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "webrick", "~> 1.9"
gem "jekyll-vitepress-theme", "~> 1.9"

# Checks the built site's internal links, anchors and images.
gem "html-proofer", "~> 5.0"
